# Dependabot will run on day 21 of each month at 03:02 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      timezone: "Europe/Berlin"
    target-branch: "master"
    open-pull-requests-limit: 30
    directories:
      - "**/*"
